- matplotlib
- plotly
- seaborn

#Instalação e importação

In [19]:
import plotly 

In [4]:
plotly.__version__

'4.4.1'

In [20]:
!pip install plotly=="4.10"

In [1]:
import plotly

In [21]:
plotly.__version__

'4.10.0'

In [22]:
import plotly.graph_objects as go

In [23]:
import plotly.express as px

In [24]:
import numpy as np

##2D

In [ ]:
fig = go.Figure()

In [ ]:
fig.show()

In [ ]:
fig.add_scatter(x = [0,1,2], y = [0,1,2])
fig.show()

In [ ]:
fig.add_scatter(x = [1,2,3], y = [4,5,6])
fig.show()

In [ ]:
fig = go.Figure()

In [ ]:
fig.add_scatter(x = [1,2,3], y = [4,5,6], mode = 'markers')

In [ ]:
fig.add_scatter(x = [7,6,5], y = [4,3,1], mode = 'lines' )

In [ ]:
fig = go.Figure()
fig.add_scatter(x = [7,6,5], y = [4,3,1], mode = 'lines', name = 'linha')

In [ ]:
fig.add_scatter(x = [1,2,5], y = [1,1,1], mode = 'markers', name = 'pontos')

$y=x^2$

In [ ]:
x = np.arange(-3,3,0.1)
x
y = x**2
y

array([9.00000000e+00, 8.41000000e+00, 7.84000000e+00, 7.29000000e+00,
       6.76000000e+00, 6.25000000e+00, 5.76000000e+00, 5.29000000e+00,
       4.84000000e+00, 4.41000000e+00, 4.00000000e+00, 3.61000000e+00,
       3.24000000e+00, 2.89000000e+00, 2.56000000e+00, 2.25000000e+00,
       1.96000000e+00, 1.69000000e+00, 1.44000000e+00, 1.21000000e+00,
       1.00000000e+00, 8.10000000e-01, 6.40000000e-01, 4.90000000e-01,
       3.60000000e-01, 2.50000000e-01, 1.60000000e-01, 9.00000000e-02,
       4.00000000e-02, 1.00000000e-02, 7.09974815e-30, 1.00000000e-02,
       4.00000000e-02, 9.00000000e-02, 1.60000000e-01, 2.50000000e-01,
       3.60000000e-01, 4.90000000e-01, 6.40000000e-01, 8.10000000e-01,
       1.00000000e+00, 1.21000000e+00, 1.44000000e+00, 1.69000000e+00,
       1.96000000e+00, 2.25000000e+00, 2.56000000e+00, 2.89000000e+00,
       3.24000000e+00, 3.61000000e+00, 4.00000000e+00, 4.41000000e+00,
       4.84000000e+00, 5.29000000e+00, 5.76000000e+00, 6.25000000e+00,
      

In [ ]:
fig = go.Figure()
fig.add_scatter(x = x, y = y, mode = 'lines')

$y=\sin(t), -2\pi \le t \le -2\pi$

In [ ]:
t = np.linspace(-2*np.pi, 2*np.pi,5)
y = np.sin(t)
fig = go.Figure()
fig.add_scatter(x = t, y = y, mode = 'lines')

In [ ]:
t = np.linspace(-2*np.pi, 2*np.pi,100)
y = np.sin(t)
fig = go.Figure()
fig.add_scatter(x = t, y = y, mode = 'lines')

vídeo até 39:31

**Exercício** plotem sin e cos no mesmo gráfico

In [ ]:
t = np.linspace(-2*np.pi, 2*np.pi,100)
y1 = np.sin(t)
y2 = np.cos(t)
fig = go.Figure()
fig.add_scatter(x = t, y = y1, mode = 'lines', name = 'Sin')
fig.add_scatter(x = t, y = y2, mode = 'lines', name = 'Cos')

In [ ]:
t = np.linspace(-2*np.pi, 2*np.pi,100)
y1 = np.sin(t)
y2 = np.cos(t)
fig = go.Figure()
fig.add_scatter(x = t, y = y1, mode = 'markers', name = 'Sin')
fig.add_scatter(x = t, y = y2, mode = 'markers', name = 'Cos')

###Cículo

$x^2 + y^2 = 1$

$$
\begin{cases}
x = Sin(t) \\
y = Cos(t)
\end{cases}$$

In [ ]:
t = np.linspace(-2*np.pi, 2*np.pi,100)
x = np.sin(t)
y = np.cos(t)
fig = go.Figure()
fig.add_scatter(x = x, y = y, mode = 'lines')

In [ ]:
t = np.linspace(-2*np.pi, 2*np.pi,100)
x = np.sin(t)
y = np.cos(t)
fig = go.Figure()
fig.add_scatter(x = x, y = y, mode = 'lines')

fig.update_layout(yaxis={'scaleanchor':'x'})

###Bar Plot

In [ ]:
fig = go.Figure()
fig.add_bar(y=[1,2,3])

##Multiple plots

In [5]:
from plotly.subplots import make_subplots

t = np.linspace(-2*np.pi, 2*np.pi,100)
x = np.sin(t)
y = np.cos(t)

fig = make_subplots(rows = 1, cols = 2)

fig.add_scatter(x = t, y = x, row = 1, col = 1, name = 'sin')
fig.add_scatter(x = t, y = y, row = 1, col = 2, name = 'cos')

fig.show()

In [ ]:
fig.update_layout(title = 'Dois Gráficos')

##3D

##Points

In [ ]:
px.scatter_3d(x=[1,2,3],y=[4,5,6],z=[7,8,9])

In [ ]:
fig = go.Figure()
fig.add_scatter3d(x=[1,2,3],y=[4,5,6],z=[7,8,9],mode='markers')


#Atualixando o layout do gráfico

fig.update_layout(scene=dict(
    xaxis=dict(range=[-5,10]),
    yaxis=dict(range=[-5,10]),
    zaxis=dict(range=[-5,10])))

In [ ]:
fig = go.Figure()
fig.add_scatter3d(x=[1,2,3],y=[4,5,6],z=[7,8,9],mode='markers')


#Atualixando o layout do gráfico

fig.update_layout(scene=dict(
    xaxis=dict(range=[-5,10],title='eixo x'),
    yaxis=dict(range=[-5,10],title='eixo y'),
    zaxis=dict(range=[-5,10],title='eixo z')))

In [ ]:
fig = go.Figure()
fig.add_scatter3d(x=[1,2,3],y=[4,5,6],z=[7,8,9],mode='markers')


#Atualixando o layout do gráfico

fig.update_layout(title = 'Pontos do Espaço',
    scene = dict(
    xaxis = dict(range = [-5,10], title = 'eixo x'),
    yaxis = dict(range = [-5,10], title = 'eixo y'),
    zaxis = dict(range = [-5,10], title = 'eixo z')),
    margin = dict(r = 20, l = 10, t = 30, b = 20))

##Curves

In [ ]:
fig = go.Figure()

t = np.linspace(-2*np.pi, 2*np.pi,100)
x = np.sin(t)
y = np.cos(t)
z = t

fig.add_scatter3d(x = x, y = y, z = z, mode = 'lines')

fig.update_layout(title = 'Helice',
    scene = dict(
    xaxis = dict(range = [-5,10], title = 'eixo x'),
    yaxis = dict(range = [-5,10], title = 'eixo y'),
    zaxis = dict(range = [-5,10], title = 'eixo z')),
    margin = dict(r = 20, l = 10, t = 30, b = 20))

In [7]:
fig = go.Figure()

t = np.linspace(-2*np.pi, 6*np.pi,100)
x = np.sin(t)
y = np.cos(t)
z = t

fig.add_scatter3d(x = x, y = y, z = z, mode = 'lines')

In [8]:
fig = go.Figure()

t = np.linspace(-2*np.pi, 6*np.pi,100)
x = np.sin(t)
y = np.cos(t)
z = t

fig.add_scatter3d(x = x, y = y, z = z, mode = 'lines', line_width = 5)

In [10]:
fig = go.Figure()

t = np.linspace(-2*np.pi, 6*np.pi,100)
x = np.sin(t)
y = np.cos(t)
z = t

fig.add_scatter3d(x = x, y = y, z = z, mode = 'markers', marker_size = 5)

##Surfaces

$z=f(x,y)$

In [13]:
xx , yy = np.mgrid[-1:1:5j, -1:1:5j]
xx

array([[-1. , -1. , -1. , -1. , -1. ],
       [-0.5, -0.5, -0.5, -0.5, -0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5,  0.5,  0.5],
       [ 1. ,  1. ,  1. ,  1. ,  1. ]])

In [14]:
yy

array([[-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ]])

In [15]:
yy.shape

(5, 5)

In [16]:
yy.flatten()

array([-1. , -0.5,  0. ,  0.5,  1. , -1. , -0.5,  0. ,  0.5,  1. , -1. ,
       -0.5,  0. ,  0.5,  1. , -1. , -0.5,  0. ,  0.5,  1. , -1. , -0.5,
        0. ,  0.5,  1. ])

In [17]:
fig = go.Figure()
fig.add_surface(x=xx.flatten(),y=yy.flatten())

In [25]:
x , y = np.meshgrid(np.linspace(-1,1,5),np.linspace(-1,1,5))
fig = go.Figure()
fig.add_surface(x=xx,y=yy)